# Form implementation generated from reading ui file 'f:\Habib University\Database Systems\Project\Project Code\supplier code\Customers.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(786, 600)
        MainWindow.setStyleSheet("QMainWindow{\n"
"    background-color: rgb(0,0,0);\n"
"}\n"
"\n"
"QMenuBar{\n"
"background-color: rgb(0,0,0);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_4 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 20, 731, 541))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setStyleSheet("QGroupBox {\n"
"    background-color: rgb(0,0,0);\n"
"    border: 1px solid black;\n"
"    color: white; \n"
"}\n"
"")
        self.groupBox_4.setObjectName("groupBox_4")
        self.groupBox = QtWidgets.QGroupBox(parent=self.groupBox_4)
        self.groupBox.setGeometry(QtCore.QRect(40, 250, 651, 271))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("QGroupBox {\n"
"    background-color: rgb(0,0,0);\n"
"    border: 1px solid black;\n"
"    color: white; \n"
"}\n"
"")
        self.groupBox.setObjectName("groupBox")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.groupBox)
        self.tableWidget.setGeometry(QtCore.QRect(30, 30, 611, 201))
        self.tableWidget.setStyleSheet("QTableWidget{\n"
"    background-color: rgb(0,0,0);\n"
"    gridline-color: rgb(255, 255, 255);\n"
"    color: rgb(255,255,255);\n"
"    border-radius: 10px;\n"
"    border: 2px solid rgb(255,255,255);\n"
"    selection-background-color: rgb(46, 46, 62);\n"
"}")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.UpdateButton = QtWidgets.QPushButton(parent=self.groupBox)
        self.UpdateButton.setGeometry(QtCore.QRect(440, 240, 81, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.UpdateButton.setFont(font)
        self.UpdateButton.setStyleSheet("QPushButton{\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 100px;\n"
"    color: #FFF;\n"
"    background-color: rgb(30, 30, 40);\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border: 2px solid rgb(53, 53, 71)\n"
"}")
        self.UpdateButton.setObjectName("UpdateButton")
        self.DeleteButton = QtWidgets.QPushButton(parent=self.groupBox)
        self.DeleteButton.setGeometry(QtCore.QRect(550, 240, 81, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.DeleteButton.setFont(font)
        self.DeleteButton.setStyleSheet("QPushButton{\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 100px;\n"
"    color: #FFF;\n"
"    background-color: rgb(30, 30, 40);\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border: 2px solid rgb(53, 53, 71)\n"
"}")
        self.DeleteButton.setObjectName("DeleteButton")
        self.reportButton = QtWidgets.QPushButton(parent=self.groupBox)
        self.reportButton.setGeometry(QtCore.QRect(340, 240, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.reportButton.setFont(font)
        self.reportButton.setStyleSheet("QPushButton{\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 100px;\n"
"    color: #FFF;\n"
"    background-color: rgb(30, 30, 40);\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border: 2px solid rgb(53, 53, 71)\n"
"}")
        self.reportButton.setObjectName("reportButton")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.groupBox_4)
        self.groupBox_2.setGeometry(QtCore.QRect(40, 110, 651, 131))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("QGroupBox {\n"
"    background-color: rgb(0,0,0);\n"
"    border: 1px solid black;\n"
"    color: white; \n"
"}\n"
"")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(10, 30, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel{\n"
"    color: #FFF;\n"
"    padding-left: 20px;\n"
"    padding-right: 10px;\n"
"}")
        self.label.setObjectName("label")
        self.customerAddPhone = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.customerAddPhone.setGeometry(QtCore.QRect(440, 30, 191, 20))
        self.customerAddPhone.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 100px;\n"
"    color: #FFF;\n"
"    background-color: rgb(30, 30, 40);\n"
"\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(53, 53, 71)\n"
"}\n"
"\n"
"QLineEdit: focus{\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"}")
        self.customerAddPhone.setObjectName("customerAddPhone")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(300, 30, 131, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel{\n"
"    color: #FFF;\n"
"    padding-left: 20px;\n"
"    padding-right: 10px;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.customerAddName = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.customerAddName.setGeometry(QtCore.QRect(100, 30, 191, 20))
        self.customerAddName.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 100px;\n"
"    color: #FFF;\n"
"    background-color: rgb(30, 30, 40);\n"
"\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(53, 53, 71)\n"
"}\n"
"\n"
"QLineEdit: focus{\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"}")
        self.customerAddName.setObjectName("customerAddName")
        self.customerAddAddress = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.customerAddAddress.setGeometry(QtCore.QRect(100, 70, 191, 20))
        self.customerAddAddress.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 100px;\n"
"    color: #FFF;\n"
"    background-color: rgb(30, 30, 40);\n"
"\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(53, 53, 71)\n"
"}\n"
"\n"
"QLineEdit: focus{\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"}")
        self.customerAddAddress.setObjectName("customerAddAddress")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel{\n"
"    color: #FFF;\n"
"    padding-left: 20px;\n"
"    padding-right: 10px;\n"
"}")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(320, 70, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel{\n"
"    color: #FFF;\n"
"    padding-left: 20px;\n"
"    padding-right: 10px;\n"
"}")
        self.label_4.setObjectName("label_4")
        self.customerAddEmail = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.customerAddEmail.setGeometry(QtCore.QRect(440, 70, 191, 20))
        self.customerAddEmail.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 100px;\n"
"    color: #FFF;\n"
"    background-color: rgb(30, 30, 40);\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(53, 53, 71)\n"
"}\n"
"\n"
"QLineEdit: focus{\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"}")
        self.customerAddEmail.setObjectName("customerAddEmail")
        self.InsertButton = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.InsertButton.setGeometry(QtCore.QRect(550, 100, 81, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.InsertButton.setFont(font)
        self.InsertButton.setStyleSheet("QPushButton{\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 100px;\n"
"    color: #FFF;\n"
"    background-color: rgb(30, 30, 40);\n"
"    padding-left: 18px;\n"
"    padding-right: 20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border: 2px solid rgb(53, 53, 71)\n"
"}")
        self.InsertButton.setObjectName("InsertButton")
        self.groupBox_3 = QtWidgets.QGroupBox(parent=self.groupBox_4)
        self.groupBox_3.setGeometry(QtCore.QRect(40, 40, 651, 61))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setStyleSheet("QGroupBox {\n"
"    background-color: rgb(0,0,0); /* Black background */\n"
"    border: 1px solid black; /* Black border */\n"
"    color: white; /* White text color for contrast */\n"
"}\n"
"")
        self.groupBox_3.setObjectName("groupBox_3")
        self.customerSearchCombo = QtWidgets.QComboBox(parent=self.groupBox_3)
        self.customerSearchCombo.setGeometry(QtCore.QRect(20, 30, 101, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.customerSearchCombo.setFont(font)
        self.customerSearchCombo.setStyleSheet("\n"
"\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: rgb(30, 30, 40);\n"
"    color: #FFF;\n"
"    selection-background-color: rgb(53, 53, 71);\n"
"    selection-color: #FFF;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QComboBox{\n"
"    background-color: rgb(30, 30, 40);\n"
"    color: rgb(255,255,255);\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    \n"
"    \n"
"}\n"
"\n"
"QComboBox:hover{\n"
"    border: 2px solid rgb(53, 53, 71);\n"
"    \n"
"    background-color: rgb(40, 40, 54);\n"
"}\n"
"")
        self.customerSearchCombo.setObjectName("customerSearchCombo")
        self.customerSearchCombo.addItem("")
        self.customerSearchCombo.addItem("")
        self.customerSearchLine = QtWidgets.QLineEdit(parent=self.groupBox_3)
        self.customerSearchLine.setGeometry(QtCore.QRect(130, 30, 401, 21))
        self.customerSearchLine.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 100px;\n"
"    color: #FFF;\n"
"    background-color: rgb(30, 30, 40);\n"
"\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(53, 53, 71)\n"
"}\n"
"\n"
"QLineEdit: focus{\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"}")
        self.customerSearchLine.setObjectName("customerSearchLine")
        self.SearchButton = QtWidgets.QPushButton(parent=self.groupBox_3)
        self.SearchButton.setGeometry(QtCore.QRect(550, 30, 81, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.SearchButton.setFont(font)
        self.SearchButton.setStyleSheet("QPushButton{\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 100px;\n"
"    color: #FFF;\n"
"    background-color: rgb(30, 30, 40);\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border: 2px solid rgb(53, 53, 71)\n"
"}")
        self.SearchButton.setObjectName("SearchButton")
        self.BackButton = QtWidgets.QPushButton(parent=self.groupBox_4)
        self.BackButton.setGeometry(QtCore.QRect(40, 20, 75, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.BackButton.setFont(font)
        self.BackButton.setStyleSheet("QPushButton{\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 100px;\n"
"    color: #FFF;\n"
"    background-color: rgb(30, 30, 40);\n"
"    padding-left: 18px;\n"
"    padding-right: 20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border: 2px solid rgb(53, 53, 71)\n"
"}")
        self.BackButton.setObjectName("BackButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 786, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Customers"))
        self.groupBox.setTitle(_translate("MainWindow", "Customer list"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "CustomerID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Contact Number"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Address"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Email"))
        self.UpdateButton.setText(_translate("MainWindow", "Update"))
        self.DeleteButton.setText(_translate("MainWindow", "Delete"))
        self.reportButton.setText(_translate("MainWindow", "Reports"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Add customers"))
        self.label.setText(_translate("MainWindow", "Name:"))
        self.label_2.setText(_translate("MainWindow", "Contact Number:"))
        self.label_3.setText(_translate("MainWindow", "Address:"))
        self.label_4.setText(_translate("MainWindow", "Email:"))
        self.InsertButton.setText(_translate("MainWindow", "Insert"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Search customer"))
        self.customerSearchCombo.setItemText(0, _translate("MainWindow", "Name"))
        self.customerSearchCombo.setItemText(1, _translate("MainWindow", "CustomerID"))
        self.SearchButton.setText(_translate("MainWindow", "Search"))
        self.BackButton.setText(_translate("MainWindow", "<--"))
