# Form implementation generated from reading ui file 'f:\Habib University\Database Systems\Project\Project Code\supplier code\finalitems.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(713, 600)
        MainWindow.setStyleSheet("QMainWindow{\n"
"    background-color: rgb(0,0,0);\n"
"}\n"
"\n"
"QMenuBar{\n"
"background-color: rgb(0,0,0);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_4 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 30, 681, 541))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setStyleSheet("QGroupBox {\n"
"    background-color: rgb(0,0,0);\n"
"    border: 1px solid black;\n"
"    color: white; \n"
"}")
        self.groupBox_4.setObjectName("groupBox_4")
        self.groupBox_3 = QtWidgets.QGroupBox(parent=self.groupBox_4)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 50, 621, 80))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.comboBox = QtWidgets.QComboBox(parent=self.groupBox_3)
        self.comboBox.setGeometry(QtCore.QRect(20, 40, 81, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("QComboBox QAbstractItemView {\n"
"    background-color: rgb(30, 30, 40);\n"
"    color: #FFF;\n"
"    selection-background-color: rgb(53, 53, 71);\n"
"    selection-color: #FFF;\n"
"}\n"
"\n"
"\n"
"QComboBox{\n"
"    background-color: rgb(30, 30, 40);\n"
"    color: rgb(255,255,255);\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"}\n"
"\n"
"QComboBox:hover{\n"
"    border: 2px solid rgb(53, 53, 71);\n"
"    \n"
"    background-color: rgb(40, 40, 54);\n"
"}")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.itemSearchLine = QtWidgets.QLineEdit(parent=self.groupBox_3)
        self.itemSearchLine.setGeometry(QtCore.QRect(110, 40, 401, 21))
        self.itemSearchLine.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 100px;\n"
"    color: #FFF;\n"
"    background-color: rgb(30, 30, 40);\n"
"\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(53, 53, 71)\n"
"}\n"
"\n"
"QLineEdit: focus{\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"}")
        self.itemSearchLine.setObjectName("itemSearchLine")
        self.SearchButton = QtWidgets.QPushButton(parent=self.groupBox_3)
        self.SearchButton.setGeometry(QtCore.QRect(530, 40, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.SearchButton.setFont(font)
        self.SearchButton.setStyleSheet("QPushButton{\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 100px;\n"
"    color: #FFF;\n"
"    background-color: rgb(30, 30, 40);\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border: 2px solid rgb(53, 53, 71)\n"
"}")
        self.SearchButton.setObjectName("SearchButton")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.groupBox_4)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 130, 621, 131))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("QGroupBox {\n"
"    background-color: rgb(0,0,0);\n"
"    border: 1px solid black;\n"
"    color: white; \n"
"}\n"
"")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(30, 30, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel{\n"
"    color: #FFF;\n"
"}")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(30, 70, 41, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel{\n"
"    color: #FFF;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(260, 30, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel{\n"
"    color: #FFF;\n"
"}")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(260, 70, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel{\n"
"    color: #FFF;\n"
"}")
        self.label_4.setObjectName("label_4")
        self.itemqtyAvailable = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.itemqtyAvailable.setGeometry(QtCore.QRect(370, 30, 131, 20))
        self.itemqtyAvailable.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 100px;\n"
"    color: #FFF;\n"
"    background-color: rgb(30, 30, 40);\n"
"\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(53, 53, 71)\n"
"}\n"
"\n"
"QLineEdit: focus{\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"}")
        self.itemqtyAvailable.setObjectName("itemqtyAvailable")
        self.itemAddID = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.itemAddID.setGeometry(QtCore.QRect(80, 70, 121, 20))
        self.itemAddID.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 100px;\n"
"    color: #FFF;\n"
"    background-color: rgb(30, 30, 40);\n"
"\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(53, 53, 71)\n"
"}\n"
"\n"
"QLineEdit: focus{\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"}")
        self.itemAddID.setObjectName("itemAddID")
        self.itemAddName = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.itemAddName.setGeometry(QtCore.QRect(80, 30, 121, 20))
        self.itemAddName.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 100px;\n"
"    color: #FFF;\n"
"    background-color: rgb(30, 30, 40);\n"
"\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(53, 53, 71)\n"
"}\n"
"\n"
"QLineEdit: focus{\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"}")
        self.itemAddName.setObjectName("itemAddName")
        self.itemAddPrice = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.itemAddPrice.setGeometry(QtCore.QRect(370, 70, 131, 20))
        self.itemAddPrice.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 100px;\n"
"    color: #FFF;\n"
"    background-color: rgb(30, 30, 40);\n"
"\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(53, 53, 71)\n"
"}\n"
"\n"
"QLineEdit: focus{\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"}")
        self.itemAddPrice.setObjectName("itemAddPrice")
        self.InsertButton = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.InsertButton.setGeometry(QtCore.QRect(530, 50, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.InsertButton.setFont(font)
        self.InsertButton.setStyleSheet("QPushButton{\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 100px;\n"
"    color: #FFF;\n"
"    background-color: rgb(30, 30, 40);\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border: 2px solid rgb(53, 53, 71)\n"
"}")
        self.InsertButton.setObjectName("InsertButton")
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(30, 100, 47, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("QLabel{\n"
"    color: #FFF;\n"
"}")
        self.label_5.setObjectName("label_5")
        self.itemAddColour = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.itemAddColour.setGeometry(QtCore.QRect(80, 100, 121, 20))
        self.itemAddColour.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 100px;\n"
"    color: #FFF;\n"
"    background-color: rgb(30, 30, 40);\n"
"\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(53, 53, 71)\n"
"}\n"
"\n"
"QLineEdit: focus{\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"}")
        self.itemAddColour.setObjectName("itemAddColour")
        self.groupBox = QtWidgets.QGroupBox(parent=self.groupBox_4)
        self.groupBox.setGeometry(QtCore.QRect(20, 270, 621, 261))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("QGroupBox {\n"
"    background-color: rgb(0,0,0);\n"
"    border: 1px solid black;\n"
"    color: white; \n"
"}")
        self.groupBox.setObjectName("groupBox")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.groupBox)
        self.tableWidget.setGeometry(QtCore.QRect(20, 20, 511, 192))
        self.tableWidget.setStyleSheet("QTableWidget{\n"
"    background-color: rgb(0,0,0);\n"
"    gridline-color: rgb(255, 255, 255);\n"
"    color: rgb(255,255,255);\n"
"    border-radius: 10px;\n"
"    border: 2px solid rgb(255,255,255);\n"
"    selection-background-color: rgb(46, 46, 62);\n"
"}")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.UpdateButton = QtWidgets.QPushButton(parent=self.groupBox)
        self.UpdateButton.setGeometry(QtCore.QRect(430, 230, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.UpdateButton.setFont(font)
        self.UpdateButton.setStyleSheet("QPushButton{\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 100px;\n"
"    color: #FFF;\n"
"    background-color: rgb(30, 30, 40);\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border: 2px solid rgb(53, 53, 71)\n"
"}")
        self.UpdateButton.setObjectName("UpdateButton")
        self.DeleteButton = QtWidgets.QPushButton(parent=self.groupBox)
        self.DeleteButton.setGeometry(QtCore.QRect(540, 230, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.DeleteButton.setFont(font)
        self.DeleteButton.setStyleSheet("QPushButton{\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 100px;\n"
"    color: #FFF;\n"
"    background-color: rgb(30, 30, 40);\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border: 2px solid rgb(53, 53, 71)\n"
"}")
        self.DeleteButton.setObjectName("DeleteButton")
        self.reportsButton = QtWidgets.QPushButton(parent=self.groupBox)
        self.reportsButton.setGeometry(QtCore.QRect(320, 230, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.reportsButton.setFont(font)
        self.reportsButton.setStyleSheet("QPushButton{\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 100px;\n"
"    color: #FFF;\n"
"    background-color: rgb(30, 30, 40);\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border: 2px solid rgb(53, 53, 71)\n"
"}")
        self.reportsButton.setObjectName("reportsButton")
        self.BackButton = QtWidgets.QPushButton(parent=self.groupBox_4)
        self.BackButton.setGeometry(QtCore.QRect(20, 20, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.BackButton.setFont(font)
        self.BackButton.setStyleSheet("QPushButton{\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 100px;\n"
"    color: #FFF;\n"
"    background-color: rgb(30, 30, 40);\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border: 2px solid rgb(53, 53, 71)\n"
"}")
        self.BackButton.setObjectName("BackButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 713, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Items"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Search items"))
        self.comboBox.setItemText(0, _translate("MainWindow", "ItemID"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Name"))
        self.SearchButton.setText(_translate("MainWindow", "Search"))
        self.groupBox_2.setTitle(_translate("MainWindow", "AddItems"))
        self.label.setText(_translate("MainWindow", "Name:"))
        self.label_2.setText(_translate("MainWindow", "ItemID:"))
        self.label_3.setText(_translate("MainWindow", "Qty Available:"))
        self.label_4.setText(_translate("MainWindow", "Price:"))
        self.InsertButton.setText(_translate("MainWindow", "Insert"))
        self.label_5.setText(_translate("MainWindow", "Colour:"))
        self.groupBox.setTitle(_translate("MainWindow", "ItemList"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ItemID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Colour"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Qty Available"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Price"))
        self.UpdateButton.setText(_translate("MainWindow", "Update"))
        self.DeleteButton.setText(_translate("MainWindow", "Delete"))
        self.reportsButton.setText(_translate("MainWindow", "Reports"))
        self.BackButton.setText(_translate("MainWindow", "<--"))
