# Form implementation generated from reading ui file 'f:\Habib University\Database Systems\Project\Project Code\supplier code\modifyPO.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(729, 291)
        MainWindow.setStyleSheet("QMainWindow{\n"
"    background-color: rgb(0,0,0);\n"
"}\n"
"\n"
"QMenuBar{\n"
"background-color: rgb(0,0,0);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 731, 241))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("QGroupBox {\n"
"    background-color: rgb(0,0,0);\n"
"    border: 1px solid white;\n"
"    color: white; \n"
"}")
        self.groupBox.setObjectName("groupBox")
        self.orderDetails = QtWidgets.QTableWidget(parent=self.groupBox)
        self.orderDetails.setGeometry(QtCore.QRect(350, 30, 341, 151))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.orderDetails.setFont(font)
        self.orderDetails.setStyleSheet("QTableWidget{\n"
"    background-color: rgb(0,0,0);\n"
"    gridline-color: rgb(255, 255, 255);\n"
"    color: rgb(255,255,255);\n"
"    border-radius: 10px;\n"
"    border: 2px solid rgb(255,255,255);\n"
"    selection-background-color: rgb(46, 46, 62);\n"
"}")
        self.orderDetails.setObjectName("orderDetails")
        self.orderDetails.setColumnCount(3)
        self.orderDetails.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.orderDetails.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.orderDetails.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.orderDetails.setHorizontalHeaderItem(2, item)
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(50, 20, 231, 211))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("QGroupBox {\n"
"    background-color: rgb(0,0,0);\n"
"    border: 1px solid white;\n"
"    color: white; \n"
"}")
        self.groupBox_2.setObjectName("groupBox_2")
        self.itemIDCombo = QtWidgets.QComboBox(parent=self.groupBox_2)
        self.itemIDCombo.setGeometry(QtCore.QRect(110, 30, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.itemIDCombo.setFont(font)
        self.itemIDCombo.setStyleSheet("QComboBox QAbstractItemView {\n"
"    background-color: rgb(30, 30, 40);\n"
"    color: #FFF;\n"
"    selection-background-color: rgb(53, 53, 71);\n"
"    selection-color: #FFF;\n"
"}\n"
"\n"
"\n"
"QComboBox{\n"
"    background-color: rgb(30, 30, 40);\n"
"    color: rgb(255,255,255);\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"}\n"
"\n"
"QComboBox:hover{\n"
"    border: 2px solid rgb(53, 53, 71);\n"
"    \n"
"    background-color: rgb(40, 40, 54);\n"
"}")
        self.itemIDCombo.setObjectName("itemIDCombo")
        self.itemIDCombo.addItem("")
        self.itemIDCombo.addItem("")
        self.itemIDCombo.addItem("")
        self.itemIDCombo.addItem("")
        self.itemIDCombo.addItem("")
        self.itemIDCombo.addItem("")
        self.itemIDCombo.addItem("")
        self.itemIDCombo.addItem("")
        self.itemIDCombo.addItem("")
        self.itemIDCombo.addItem("")
        self.itemIDCombo.addItem("")
        self.itemIDCombo.addItem("")
        self.itemIDCombo.addItem("")
        self.itemIDCombo.addItem("")
        self.itemIDCombo.addItem("")
        self.itemNameCombo = QtWidgets.QComboBox(parent=self.groupBox_2)
        self.itemNameCombo.setGeometry(QtCore.QRect(110, 60, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.itemNameCombo.setFont(font)
        self.itemNameCombo.setStyleSheet("QComboBox QAbstractItemView {\n"
"    background-color: rgb(30, 30, 40);\n"
"    color: #FFF;\n"
"    selection-background-color: rgb(53, 53, 71);\n"
"    selection-color: #FFF;\n"
"}\n"
"\n"
"\n"
"QComboBox{\n"
"    background-color: rgb(30, 30, 40);\n"
"    color: rgb(255,255,255);\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"}\n"
"\n"
"QComboBox:hover{\n"
"    border: 2px solid rgb(53, 53, 71);\n"
"    \n"
"    background-color: rgb(40, 40, 54);\n"
"}")
        self.itemNameCombo.setObjectName("itemNameCombo")
        self.itemNameCombo.addItem("")
        self.itemNameCombo.addItem("")
        self.itemNameCombo.addItem("")
        self.itemNameCombo.addItem("")
        self.itemNameCombo.addItem("")
        self.unitPriceLine = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.unitPriceLine.setGeometry(QtCore.QRect(110, 150, 113, 20))
        self.unitPriceLine.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 100px;\n"
"    color: #FFF;\n"
"    background-color: rgb(30, 30, 40);\n"
"\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(53, 53, 71)\n"
"}\n"
"\n"
"QLineEdit: focus{\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"}")
        self.unitPriceLine.setObjectName("unitPriceLine")
        self.addItemButton = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.addItemButton.setGeometry(QtCore.QRect(140, 180, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.addItemButton.setFont(font)
        self.addItemButton.setStyleSheet("QPushButton{\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 100px;\n"
"    color: #FFF;\n"
"    background-color: rgb(30, 30, 40);\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border: 2px solid rgb(53, 53, 71)\n"
"}")
        self.addItemButton.setObjectName("addItemButton")
        self.label = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(20, 90, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel{\n"
"    color: #FFF;\n"
"}")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(20, 120, 35, 10))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel{\n"
"    color: #FFF;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(20, 150, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel{\n"
"    color: #FFF;\n"
"}")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(20, 60, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel{\n"
"    color: #FFF;\n"
"}")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(20, 30, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("QLabel{\n"
"    color: #FFF;\n"
";\n"
"}")
        self.label_5.setObjectName("label_5")
        self.quantityLine = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.quantityLine.setGeometry(QtCore.QRect(110, 90, 113, 20))
        self.quantityLine.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 100px;\n"
"    color: #FFF;\n"
"    background-color: rgb(30, 30, 40);\n"
"\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(53, 53, 71)\n"
"}\n"
"\n"
"QLineEdit: focus{\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"}")
        self.quantityLine.setObjectName("quantityLine")
        self.colourLine = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.colourLine.setGeometry(QtCore.QRect(110, 120, 113, 20))
        self.colourLine.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 100px;\n"
"    color: #FFF;\n"
"    background-color: rgb(30, 30, 40);\n"
"\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(53, 53, 71)\n"
"}\n"
"\n"
"QLineEdit: focus{\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"}")
        self.colourLine.setObjectName("colourLine")
        self.removeItem = QtWidgets.QPushButton(parent=self.groupBox)
        self.removeItem.setGeometry(QtCore.QRect(480, 200, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.removeItem.setFont(font)
        self.removeItem.setStyleSheet("QPushButton{\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 100px;\n"
"    color: #FFF;\n"
"    background-color: rgb(30, 30, 40);\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border: 2px solid rgb(53, 53, 71)\n"
"}")
        self.removeItem.setObjectName("removeItem")
        self.doneButton = QtWidgets.QPushButton(parent=self.groupBox)
        self.doneButton.setGeometry(QtCore.QRect(600, 200, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.doneButton.setFont(font)
        self.doneButton.setStyleSheet("QPushButton{\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 100px;\n"
"    color: #FFF;\n"
"    background-color: rgb(30, 30, 40);\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border: 2px solid rgb(53, 53, 71)\n"
"}")
        self.doneButton.setObjectName("doneButton")
        self.updateItem = QtWidgets.QPushButton(parent=self.groupBox)
        self.updateItem.setGeometry(QtCore.QRect(350, 200, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.updateItem.setFont(font)
        self.updateItem.setStyleSheet("QPushButton{\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 100px;\n"
"    color: #FFF;\n"
"    background-color: rgb(30, 30, 40);\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border: 2px solid rgb(53, 53, 71)\n"
"}")
        self.updateItem.setObjectName("updateItem")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 729, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Modify PO"))
        item = self.orderDetails.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ItemID"))
        item = self.orderDetails.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Quantity"))
        item = self.orderDetails.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Cost"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Add Items to PO"))
        self.itemIDCombo.setItemText(0, _translate("MainWindow", "101"))
        self.itemIDCombo.setItemText(1, _translate("MainWindow", "102"))
        self.itemIDCombo.setItemText(2, _translate("MainWindow", "103"))
        self.itemIDCombo.setItemText(3, _translate("MainWindow", "104"))
        self.itemIDCombo.setItemText(4, _translate("MainWindow", "201"))
        self.itemIDCombo.setItemText(5, _translate("MainWindow", "202"))
        self.itemIDCombo.setItemText(6, _translate("MainWindow", "203"))
        self.itemIDCombo.setItemText(7, _translate("MainWindow", "204"))
        self.itemIDCombo.setItemText(8, _translate("MainWindow", "301"))
        self.itemIDCombo.setItemText(9, _translate("MainWindow", "302"))
        self.itemIDCombo.setItemText(10, _translate("MainWindow", "303"))
        self.itemIDCombo.setItemText(11, _translate("MainWindow", "304"))
        self.itemIDCombo.setItemText(12, _translate("MainWindow", "401"))
        self.itemIDCombo.setItemText(13, _translate("MainWindow", "402"))
        self.itemIDCombo.setItemText(14, _translate("MainWindow", "501"))
        self.itemNameCombo.setItemText(0, _translate("MainWindow", "Tumbler"))
        self.itemNameCombo.setItemText(1, _translate("MainWindow", "Metallic Bottle"))
        self.itemNameCombo.setItemText(2, _translate("MainWindow", "Metallic Straw"))
        self.itemNameCombo.setItemText(3, _translate("MainWindow", "Tote Bag"))
        self.itemNameCombo.setItemText(4, _translate("MainWindow", "Glass Tumbler"))
        self.addItemButton.setText(_translate("MainWindow", "Add Item "))
        self.label.setText(_translate("MainWindow", "Quantity"))
        self.label_2.setText(_translate("MainWindow", "Color:"))
        self.label_3.setText(_translate("MainWindow", "Unit Price:"))
        self.label_4.setText(_translate("MainWindow", "Item Name:"))
        self.label_5.setText(_translate("MainWindow", "Item ID"))
        self.removeItem.setText(_translate("MainWindow", "Remove Item"))
        self.doneButton.setText(_translate("MainWindow", "Done"))
        self.updateItem.setText(_translate("MainWindow", "Update Item"))
