# Form implementation generated from reading ui file 'f:\Habib University\Database Systems\Project\Project Code\supplier code\newSupplierList.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(771, 521)
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("QMainWindow{\n"
"    background-color: rgb(0,0,0);\n"
"}\n"
"\n"
"QMenuBar{\n"
"background-color: rgb(0,0,0);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 751, 451))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("QGroupBox {\n"
"    background-color: rgb(0,0,0);\n"
"    border: 1px solid black;\n"
"    color: white; \n"
"}")
        self.groupBox.setObjectName("groupBox")
        self.supplierList = QtWidgets.QTableWidget(parent=self.groupBox)
        self.supplierList.setGeometry(QtCore.QRect(10, 220, 401, 171))
        self.supplierList.setMaximumSize(QtCore.QSize(401, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.supplierList.setFont(font)
        self.supplierList.setStyleSheet("QTableWidget{\n"
"    background-color: rgb(0,0,0);\n"
"    gridline-color: rgb(255, 255, 255);\n"
"    color: rgb(255,255,255);\n"
"    border-radius: 10px;\n"
"    border: 2px solid rgb(255,255,255);\n"
"    selection-background-color: rgb(46, 46, 62);\n"
"}")
        self.supplierList.setWordWrap(True)
        self.supplierList.setObjectName("supplierList")
        self.supplierList.setColumnCount(6)
        self.supplierList.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.supplierList.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.supplierList.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.supplierList.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.supplierList.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.supplierList.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.supplierList.setHorizontalHeaderItem(5, item)
        self.supplierUpdateButton = QtWidgets.QPushButton(parent=self.groupBox)
        self.supplierUpdateButton.setGeometry(QtCore.QRect(510, 400, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.supplierUpdateButton.setFont(font)
        self.supplierUpdateButton.setStyleSheet("QPushButton{\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 100px;\n"
"    color: #FFF;\n"
"    background-color: rgb(30, 30, 40);\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border: 2px solid rgb(53, 53, 71)\n"
"}")
        self.supplierUpdateButton.setObjectName("supplierUpdateButton")
        self.groupBox_3 = QtWidgets.QGroupBox(parent=self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 50, 731, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setStyleSheet("QGroupBox {\n"
"    background-color: rgb(0,0,0);\n"
"    border: 1px solid black;\n"
"    color: white; \n"
"}")
        self.groupBox_3.setObjectName("groupBox_3")
        self.supplierSearchCombo = QtWidgets.QComboBox(parent=self.groupBox_3)
        self.supplierSearchCombo.setGeometry(QtCore.QRect(30, 20, 111, 21))
        self.supplierSearchCombo.setStyleSheet("QComboBox QAbstractItemView {\n"
"    background-color: rgb(30, 30, 40);\n"
"    color: #FFF;\n"
"    selection-background-color: rgb(53, 53, 71);\n"
"    selection-color: #FFF;\n"
"}\n"
"\n"
"\n"
"QComboBox{\n"
"    background-color: rgb(30, 30, 40);\n"
"    color: rgb(255,255,255);\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"}\n"
"\n"
"QComboBox:hover{\n"
"    border: 2px solid rgb(53, 53, 71);\n"
"    \n"
"    background-color: rgb(40, 40, 54);\n"
"}")
        self.supplierSearchCombo.setObjectName("supplierSearchCombo")
        self.supplierSearchCombo.addItem("")
        self.supplierSearchCombo.addItem("")
        self.supplierSearchLine = QtWidgets.QLineEdit(parent=self.groupBox_3)
        self.supplierSearchLine.setGeometry(QtCore.QRect(170, 20, 421, 20))
        self.supplierSearchLine.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 100px;\n"
"    color: #FFF;\n"
"    background-color: rgb(30, 30, 40);\n"
"\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(53, 53, 71)\n"
"}\n"
"\n"
"QLineEdit: focus{\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"}")
        self.supplierSearchLine.setObjectName("supplierSearchLine")
        self.supplierSearchButton = QtWidgets.QPushButton(parent=self.groupBox_3)
        self.supplierSearchButton.setGeometry(QtCore.QRect(610, 20, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.supplierSearchButton.setFont(font)
        self.supplierSearchButton.setStyleSheet("QPushButton{\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 100px;\n"
"    color: #FFF;\n"
"    background-color: rgb(30, 30, 40);\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border: 2px solid rgb(53, 53, 71)\n"
"}")
        self.supplierSearchButton.setObjectName("supplierSearchButton")
        self.supplierDeleteButton = QtWidgets.QPushButton(parent=self.groupBox)
        self.supplierDeleteButton.setGeometry(QtCore.QRect(620, 400, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.supplierDeleteButton.setFont(font)
        self.supplierDeleteButton.setStyleSheet("QPushButton{\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 100px;\n"
"    color: #FFF;\n"
"    background-color: rgb(30, 30, 40);\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border: 2px solid rgb(53, 53, 71)\n"
"}c")
        self.supplierDeleteButton.setObjectName("supplierDeleteButton")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 100, 731, 111))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("QGroupBox {\n"
"    background-color: rgb(0,0,0);\n"
"    border: 1px solid black;\n"
"    color: white; \n"
"}")
        self.groupBox_2.setObjectName("groupBox_2")
        self.supplierAddName = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.supplierAddName.setGeometry(QtCore.QRect(110, 20, 141, 20))
        self.supplierAddName.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 100px;\n"
"    color: #FFF;\n"
"    background-color: rgb(30, 30, 40);\n"
"\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(53, 53, 71)\n"
"}\n"
"\n"
"QLineEdit: focus{\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"}")
        self.supplierAddName.setObjectName("supplierAddName")
        self.supplierAddContact = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.supplierAddContact.setGeometry(QtCore.QRect(370, 20, 131, 20))
        self.supplierAddContact.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 100px;\n"
"    color: #FFF;\n"
"    background-color: rgb(30, 30, 40);\n"
"\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(53, 53, 71)\n"
"}\n"
"\n"
"QLineEdit: focus{\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"}")
        self.supplierAddContact.setObjectName("supplierAddContact")
        self.supplierAddEmail = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.supplierAddEmail.setGeometry(QtCore.QRect(110, 60, 141, 20))
        self.supplierAddEmail.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 100px;\n"
"    color: #FFF;\n"
"    background-color: rgb(30, 30, 40);\n"
"\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(53, 53, 71)\n"
"}\n"
"\n"
"QLineEdit: focus{\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"}")
        self.supplierAddEmail.setObjectName("supplierAddEmail")
        self.supplierAddCity = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.supplierAddCity.setGeometry(QtCore.QRect(370, 60, 131, 20))
        self.supplierAddCity.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 100px;\n"
"    color: #FFF;\n"
"    background-color: rgb(30, 30, 40);\n"
"\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(53, 53, 71)\n"
"}\n"
"\n"
"QLineEdit: focus{\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"}")
        self.supplierAddCity.setObjectName("supplierAddCity")
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(20, 20, 41, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("QLabel{\n"
"    color: #FFF;\n"
"}")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(270, 20, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("QLabel{\n"
"    color: #FFF;\n"
"}")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(20, 60, 41, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("QLabel{\n"
"    color: #FFF;\n"
"}")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(280, 60, 41, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("QLabel{\n"
"    color: #FFF;\n"
"}")
        self.label_8.setObjectName("label_8")
        self.supplierInsertButton = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.supplierInsertButton.setGeometry(QtCore.QRect(620, 60, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.supplierInsertButton.setFont(font)
        self.supplierInsertButton.setStyleSheet("QPushButton{\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 100px;\n"
"    color: #FFF;\n"
"    background-color: rgb(30, 30, 40);\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border: 2px solid rgb(53, 53, 71)\n"
"}")
        self.supplierInsertButton.setObjectName("supplierInsertButton")
        self.label = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(520, 20, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel{\n"
"    color: #FFF;\n"
"}")
        self.label.setObjectName("label")
        self.supplierAddCountry = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.supplierAddCountry.setGeometry(QtCore.QRect(580, 20, 131, 20))
        self.supplierAddCountry.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 100px;\n"
"    color: #FFF;\n"
"    background-color: rgb(30, 30, 40);\n"
"\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(53, 53, 71)\n"
"}\n"
"\n"
"QLineEdit: focus{\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"}")
        self.supplierAddCountry.setObjectName("supplierAddCountry")
        self.exitButton = QtWidgets.QPushButton(parent=self.groupBox)
        self.exitButton.setGeometry(QtCore.QRect(30, 20, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.exitButton.setFont(font)
        self.exitButton.setStyleSheet("QPushButton{\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 100px;\n"
"    color: #FFF;\n"
"    background-color: rgb(30, 30, 40);\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border: 2px solid rgb(53, 53, 71)\n"
"}")
        self.exitButton.setObjectName("exitButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 771, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Suppliers"))
        item = self.supplierList.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "SupplierID"))
        item = self.supplierList.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Supplier Name"))
        item = self.supplierList.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "City"))
        item = self.supplierList.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Country"))
        item = self.supplierList.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Email"))
        item = self.supplierList.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Contact. No"))
        self.supplierUpdateButton.setText(_translate("MainWindow", "Update"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Search Supplier"))
        self.supplierSearchCombo.setItemText(0, _translate("MainWindow", "Name"))
        self.supplierSearchCombo.setItemText(1, _translate("MainWindow", "SupplierID"))
        self.supplierSearchButton.setText(_translate("MainWindow", "Search"))
        self.supplierDeleteButton.setText(_translate("MainWindow", "Delete"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Add Supplier"))
        self.label_5.setText(_translate("MainWindow", "Name:"))
        self.label_6.setText(_translate("MainWindow", "Contact Number:"))
        self.label_7.setText(_translate("MainWindow", "Email:"))
        self.label_8.setText(_translate("MainWindow", "City:"))
        self.supplierInsertButton.setText(_translate("MainWindow", "Insert"))
        self.label.setText(_translate("MainWindow", "Country:"))
        self.exitButton.setText(_translate("MainWindow", "<--"))
