# Form implementation generated from reading ui file 'f:\Habib University\Database Systems\Project\Project Code\supplier code\purchaseOrderList.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(706, 386)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("QMainWindow{\n"
"    background-color: rgb(0,0,0);\n"
"}\n"
"\n"
"QMenuBar{\n"
"background-color: rgb(0,0,0);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 661, 341))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("QGroupBox {\n"
"    background-color: rgb(0,0,0);\n"
"    border: 1px solid white;\n"
"    color: white; \n"
"}QgroupBox{\n"
"\n"
"    color: rgb(255,255, 255);}")
        self.groupBox.setObjectName("groupBox")
        self.orderList = QtWidgets.QTableWidget(parent=self.groupBox)
        self.orderList.setGeometry(QtCore.QRect(30, 90, 531, 231))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.orderList.setFont(font)
        self.orderList.setStyleSheet("QTableWidget{\n"
"    background-color: rgb(0,0,0);\n"
"    gridline-color: rgb(255, 255, 255);\n"
"    color: rgb(255,255,255);\n"
"    border-radius: 10px;\n"
"    border: 2px solid rgb(255,255,255);\n"
"    selection-background-color: rgb(46, 46, 62);\n"
"}")
        self.orderList.setObjectName("orderList")
        self.orderList.setColumnCount(4)
        self.orderList.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.orderList.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.orderList.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.orderList.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.orderList.setHorizontalHeaderItem(3, item)
        self.modifyOrder = QtWidgets.QPushButton(parent=self.groupBox)
        self.modifyOrder.setGeometry(QtCore.QRect(570, 130, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.modifyOrder.setFont(font)
        self.modifyOrder.setStyleSheet("QPushButton{\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 100px;\n"
"    color: #FFF;\n"
"    background-color: rgb(30, 30, 40);\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border: 2px solid rgb(53, 53, 71)\n"
"}")
        self.modifyOrder.setObjectName("modifyOrder")
        self.addOrder = QtWidgets.QPushButton(parent=self.groupBox)
        self.addOrder.setGeometry(QtCore.QRect(570, 90, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.addOrder.setFont(font)
        self.addOrder.setStyleSheet("QPushButton{\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 100px;\n"
"    color: #FFF;\n"
"    background-color: rgb(30, 30, 40);\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border: 2px solid rgb(53, 53, 71)\n"
"}")
        self.addOrder.setObjectName("addOrder")
        self.viewOrder = QtWidgets.QPushButton(parent=self.groupBox)
        self.viewOrder.setGeometry(QtCore.QRect(570, 170, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.viewOrder.setFont(font)
        self.viewOrder.setStyleSheet("QPushButton{\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 100px;\n"
"    color: #FFF;\n"
"    background-color: rgb(30, 30, 40);\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border: 2px solid rgb(53, 53, 71)\n"
"}")
        self.viewOrder.setObjectName("viewOrder")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 20, 651, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setAutoFillBackground(False)
        self.groupBox_2.setStyleSheet("QGroupBox {\n"
"    background-color: rgb(0,0,0);\n"
"    border: 1px solid white;\n"
"    color: white; \n"
"}")
        self.groupBox_2.setObjectName("groupBox_2")
        self.searchOrderCombo = QtWidgets.QComboBox(parent=self.groupBox_2)
        self.searchOrderCombo.setGeometry(QtCore.QRect(30, 20, 101, 22))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.searchOrderCombo.setFont(font)
        self.searchOrderCombo.setStyleSheet("QComboBox QAbstractItemView {\n"
"    background-color: rgb(30, 30, 40);\n"
"    color: #FFF;\n"
"    selection-background-color: rgb(53, 53, 71);\n"
"    selection-color: #FFF;\n"
"}\n"
"\n"
"\n"
"QComboBox{\n"
"    background-color: rgb(30, 30, 40);\n"
"    color: rgb(255,255,255);\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"}\n"
"\n"
"QComboBox:hover{\n"
"    border: 2px solid rgb(53, 53, 71);\n"
"    \n"
"    background-color: rgb(40, 40, 54);\n"
"}")
        self.searchOrderCombo.setObjectName("searchOrderCombo")
        self.searchOrderCombo.addItem("")
        self.searchOrderCombo.addItem("")
        self.searchOrderLine = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.searchOrderLine.setGeometry(QtCore.QRect(150, 20, 361, 21))
        self.searchOrderLine.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 100px;\n"
"    color: #FFF;\n"
"    background-color: rgb(30, 30, 40);\n"
"\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(53, 53, 71)\n"
"}\n"
"\n"
"QLineEdit: focus{\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"}")
        self.searchOrderLine.setObjectName("searchOrderLine")
        self.searchOrders = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.searchOrders.setGeometry(QtCore.QRect(570, 10, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.searchOrders.setFont(font)
        self.searchOrders.setStyleSheet("QPushButton{\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 100px;\n"
"    color: #FFF;\n"
"    background-color: rgb(30, 30, 40);\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border: 2px solid rgb(53, 53, 71)\n"
"}")
        self.searchOrders.setObjectName("searchOrders")
        self.deleteOrder = QtWidgets.QPushButton(parent=self.groupBox)
        self.deleteOrder.setGeometry(QtCore.QRect(570, 210, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.deleteOrder.setFont(font)
        self.deleteOrder.setStyleSheet("QPushButton{\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 100px;\n"
"    color: #FFF;\n"
"    background-color: rgb(30, 30, 40);\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border: 2px solid rgb(53, 53, 71)\n"
"}")
        self.deleteOrder.setObjectName("deleteOrder")
        self.exitButton = QtWidgets.QPushButton(parent=self.groupBox)
        self.exitButton.setGeometry(QtCore.QRect(570, 252, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.exitButton.setFont(font)
        self.exitButton.setStyleSheet("QPushButton{\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 100px;\n"
"    color: #FFF;\n"
"    background-color: rgb(30, 30, 40);\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border: 2px solid rgb(53, 53, 71)\n"
"}")
        self.exitButton.setObjectName("exitButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 706, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "List of Purchase Orders"))
        item = self.orderList.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "PO Number"))
        item = self.orderList.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "SupplierID"))
        item = self.orderList.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Amount"))
        item = self.orderList.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Order Date"))
        self.modifyOrder.setText(_translate("MainWindow", "Modify"))
        self.addOrder.setText(_translate("MainWindow", "Add"))
        self.viewOrder.setText(_translate("MainWindow", "View PO"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Search Purchase Order"))
        self.searchOrderCombo.setItemText(0, _translate("MainWindow", "PO Number"))
        self.searchOrderCombo.setItemText(1, _translate("MainWindow", "SupplierID"))
        self.searchOrders.setText(_translate("MainWindow", "Search"))
        self.deleteOrder.setText(_translate("MainWindow", "Delete"))
        self.exitButton.setText(_translate("MainWindow", "Exit"))
