# Form implementation generated from reading ui file 'f:\Habib University\Database Systems\Project\Project Code\supplier code\viewOrder.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(489, 327)
        MainWindow.setStyleSheet("QMainWindow{\n"
"    background-color: rgb(0,0,0);\n"
"}\n"
"\n"
"QMenuBar{\n"
"background-color: rgb(0,0,0);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 461, 281))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("QGroupBox {\n"
"    background-color: rgb(0,0,0);\n"
"    border: 1px solid black;\n"
"    color: white; \n"
"}")
        self.groupBox.setObjectName("groupBox")
        self.viewOrderTable = QtWidgets.QTableWidget(parent=self.groupBox)
        self.viewOrderTable.setGeometry(QtCore.QRect(10, 60, 441, 171))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.viewOrderTable.setFont(font)
        self.viewOrderTable.setStyleSheet("QTableWidget{\n"
"    background-color: rgb(0,0,0);\n"
"    gridline-color: rgb(255, 255, 255);\n"
"    color: rgb(255,255,255);\n"
"    border-radius: 10px;\n"
"    border: 2px solid rgb(255,255,255);\n"
"    selection-background-color: rgb(46, 46, 62);\n"
"}")
        self.viewOrderTable.setObjectName("viewOrderTable")
        self.viewOrderTable.setColumnCount(4)
        self.viewOrderTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.viewOrderTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.viewOrderTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.viewOrderTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.viewOrderTable.setHorizontalHeaderItem(3, item)
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 30, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel{\n"
"    color: #FFF;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.viewCustomerIDLine = QtWidgets.QLineEdit(parent=self.groupBox)
        self.viewCustomerIDLine.setGeometry(QtCore.QRect(100, 30, 141, 20))
        self.viewCustomerIDLine.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 100px;\n"
"    color: #FFF;\n"
"    background-color: rgb(30, 30, 40);\n"
"\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(53, 53, 71)\n"
"}\n"
"\n"
"QLineEdit: focus{\n"
"    border: 2px solid rgb(85, 170, 255);\n"
"}")
        self.viewCustomerIDLine.setObjectName("viewCustomerIDLine")
        self.viewExitButton = QtWidgets.QPushButton(parent=self.groupBox)
        self.viewExitButton.setGeometry(QtCore.QRect(370, 240, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.viewExitButton.setFont(font)
        self.viewExitButton.setStyleSheet("QPushButton{\n"
"    border: 2px solid rgb(37, 39, 48);\n"
"    border-radius: 100px;\n"
"    color: #FFF;\n"
"    background-color: rgb(30, 30, 40);\n"
"    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border: 2px solid rgb(53, 53, 71)\n"
"}")
        self.viewExitButton.setObjectName("viewExitButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 489, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Order Details"))
        item = self.viewOrderTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Order Number"))
        item = self.viewOrderTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "ItemID"))
        item = self.viewOrderTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Price Per Unit"))
        item = self.viewOrderTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Quantity Bought"))
        self.label_2.setText(_translate("MainWindow", "CustomerID:"))
        self.viewExitButton.setText(_translate("MainWindow", "Exit"))
